In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
with open('./1661-0.txt', 'r', encoding='latin-1') as file:
    content = file.read()

In [5]:
content=content.split("\n")

In [7]:
content

['',
 "Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle",
 '',
 'This eBook is for the use of anyone anywhere at no cost and with',
 'almost no restrictions whatsoever.  You may copy it, give it away or',
 're-use it under the terms of the Project Gutenberg License included',
 'with this eBook or online at www.gutenberg.net',
 '',
 '',
 'Title: The Adventures of Sherlock Holmes',
 '',
 'Author: Arthur Conan Doyle',
 '',
 'Release Date: November 29, 2002 [EBook #1661]',
 'Last Updated: May 20, 2019',
 '',
 'Language: English',
 '',
 'Character set encoding: UTF-8',
 '',
 '*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES ***',
 '',
 '',
 '',
 'Produced by an anonymous Project Gutenberg volunteer and Jose Menendez',
 '',
 '',
 '',
 'cover',
 '',
 '',
 '',
 'The Adventures of Sherlock Holmes',
 '',
 '',
 '',
 'by Arthur Conan Doyle',
 '',
 '',
 '',
 'Contents',
 '',
 '',
 '   I.     A Scandal in Bohemia',
 '   II.    The Red-Headed 

In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
tokenizer=Tokenizer()

In [13]:
tokenizer.fit_on_texts(content)

In [15]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'a': 5,
 'i': 6,
 'â\x80\x9d': 7,
 'in': 8,
 'that': 9,
 'it': 10,
 'he': 11,
 'was': 12,
 'you': 13,
 'his': 14,
 'is': 15,
 'my': 16,
 'have': 17,
 'with': 18,
 'as': 19,
 'had': 20,
 'at': 21,
 'which': 22,
 'for': 23,
 'be': 24,
 'not': 25,
 'me': 26,
 'but': 27,
 'from': 28,
 'we': 29,
 'this': 30,
 'said': 31,
 'upon': 32,
 'there': 33,
 'holmes': 34,
 'him': 35,
 'so': 36,
 'her': 37,
 'she': 38,
 'all': 39,
 'â\x80\x99': 40,
 'been': 41,
 'your': 42,
 'on': 43,
 'very': 44,
 'by': 45,
 'one': 46,
 'are': 47,
 'â\x80\x9ci': 48,
 'were': 49,
 'an': 50,
 'no': 51,
 'would': 52,
 'out': 53,
 'what': 54,
 'then': 55,
 'up': 56,
 'when': 57,
 'man': 58,
 'could': 59,
 'has': 60,
 'do': 61,
 'into': 62,
 'or': 63,
 'little': 64,
 'will': 65,
 'who': 66,
 'mr': 67,
 'if': 68,
 'some': 69,
 'down': 70,
 'see': 71,
 'now': 72,
 'our': 73,
 'should': 74,
 'may': 75,
 'am': 76,
 'us': 77,
 'over': 78,
 'they': 79,
 'can': 80,
 'more': 81,
 'think'

In [17]:
len(tokenizer.word_index)

8931

In [19]:
input_sequence=[]
for i in content:
    tokenised=tokenizer.texts_to_sequences([i])[0]
    if(len(tokenised)==0):
        continue
    else:
        for j in range(1,len(tokenised)):
            input_sequence.append(tokenised[:j+1])

In [21]:
input_sequence

[[145, 4790],
 [145, 4790, 1],
 [145, 4790, 1, 1020],
 [145, 4790, 1, 1020, 4],
 [145, 4790, 1, 1020, 4, 128],
 [145, 4790, 1, 1020, 4, 128, 34],
 [145, 4790, 1, 1020, 4, 128, 34, 45],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611, 2235],
 [145, 4790, 1, 1020, 4, 128, 34, 45, 611, 2235, 2236],
 [30, 1021],
 [30, 1021, 15],
 [30, 1021, 15, 23],
 [30, 1021, 15, 23, 1],
 [30, 1021, 15, 23, 1, 275],
 [30, 1021, 15, 23, 1, 275, 4],
 [30, 1021, 15, 23, 1, 275, 4, 394],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676, 2],
 [30, 1021, 15, 23, 1, 275, 4, 394, 2237, 21, 51, 1676, 2, 18],
 [572, 51],
 [572, 51, 3398],
 [572, 51, 3398, 3399],
 [572, 51, 3398, 3399, 13],
 [572, 51, 3398, 3399, 13, 75],
 [572, 51, 3398, 3399, 13, 75, 817],
 [572, 51, 3398, 33

In [31]:
from tensorflow.keras.utils import pad_sequences

In [33]:
padded_seq=pad_sequences(input_sequence,padding="pre")

In [35]:
padded_seq

array([[   0,    0,    0, ...,    0,  145, 4790],
       [   0,    0,    0, ...,  145, 4790,    1],
       [   0,    0,    0, ..., 4790,    1, 1020],
       ...,
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358],
       [   0,    0,    0, ...,   83,  358, 1673]])

In [37]:
X=padded_seq[:,:-1]
Y=padded_seq[:,-1]

In [39]:
X

array([[   0,    0,    0, ...,    0,    0,  145],
       [   0,    0,    0, ...,    0,  145, 4790],
       [   0,    0,    0, ...,  145, 4790,    1],
       ...,
       [   0,    0,    0, ..., 8931,    3,  360],
       [   0,    0,    0, ...,    3,  360,   83],
       [   0,    0,    0, ...,  360,   83,  358]])

In [41]:
X.shape

(101619, 19)

In [43]:
Y

array([4790,    1, 1020, ...,   83,  358, 1673])

In [45]:
Y.shape

(101619,)

In [47]:
Y=pd.get_dummies(Y,dtype="int")

In [48]:
Y.shape

(101619, 8192)

In [51]:
X.shape

(101619, 19)

In [53]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM

In [55]:
model=Sequential()
model.add(Embedding(input_dim=8932,output_dim=100,input_length=19))
model.add(LSTM(150,return_sequences=True))   ### 150 is no. of nodes
model.add(LSTM(150))
model.add(Dense(8192,activation="softmax"))

D:\Anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [57]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.compile(loss="categorical_crossentropy",metrics=["accuracy"],optimizer="Adam")

In [63]:
history=model.fit(X,Y,epochs=10,validation_split=0.2,verbose=1)

Epoch 1/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 84s 32ms/step - accuracy: 0.0569 - loss: 6.6610 - val_accuracy: 0.0675 - val_loss: 6.4378
Epoch 2/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 84s 33ms/step - accuracy: 0.0878 - loss: 5.8277 - val_accuracy: 0.0980 - val_loss: 6.2504
Epoch 3/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 85s 33ms/step - accuracy: 0.1162 - loss: 5.4699 - val_accuracy: 0.1103 - val_loss: 6.2783
Epoch 4/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 86s 34ms/step - accuracy: 0.1320 - loss: 5.2362 - val_accuracy: 0.1160 - val_loss: 6.3290
Epoch 5/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 85s 34ms/step - accuracy: 0.1453 - loss: 5.0162 - val_accuracy: 0.1224 - val_loss: 6.4335
Epoch 6/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 86s 34ms/step - accuracy: 0.1547 - loss: 4.8236 - val_accuracy: 0.1220 - val_loss: 6.5257
Epoch 7/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 86s 34ms/step - accuracy: 0.1657 - loss: 4.6451 - val_accuracy: 0.1260 - val_loss: 6.6559
Epoch 8/10
2541/2541 ━━━━━━━━━━━━━━━━━━━━ 85s 34ms/step - accuracy: 0.1750 -

In [65]:
text="this"
tokenised=tokenizer.texts_to_sequences([text])[0]

In [67]:
padded=pad_sequences([tokenised],maxlen=19,padding="pre")

In [69]:
pos=np.argmax(model.predict(padded))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 298ms/step


In [71]:
for word,index in tokenizer.word_index.items():
    if(index==pos):
        print(word)

right


In [99]:
import time
text="with a"
for i in range(10):
    tokenised=tokenizer.texts_to_sequences([text])[0]
    padded=pad_sequences([tokenised],maxlen=19,padding="pre")
    pos=np.argmax(model.predict(padded))
    for word,index in tokenizer.word_index.items():
        if(index==pos):
            text=text + " " + word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
with a or
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
with a or there
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
with a or there his
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
with a or there his bed
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
with a or there his bed as
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
with a or there his bed as a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
with a or there his bed as a thought
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
with a or there his bed as a thought to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
